#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Fri Mar 06 05:52:41 GMT 2026
android.nonTransitiveRClass=true
systemProp.user.language=en
systemProp.user.country=US
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8
android.useAndroidX=true
